# Generated by Django 4.2.14 on 2024-07-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskitem',
            old_name='headline',
            new_name='title',
        ),
    ]
