# Generated by Django 4.2.14 on 2024-07-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0004_alter_taskitem_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task_board.taskitem')),
            ],
        ),
    ]
