# Generated by Django 4.2.14 on 2024-07-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0005_subtaskitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtaskitem',
            old_name='text',
            new_name='title',
        ),
    ]
