# Generated by Django 4.2.14 on 2024-07-26 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0007_contactsgl_taskitem_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsgl',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='category',
            field=models.CharField(default='Others', max_length=50),
        ),
    ]
