# Generated by Django 4.2.14 on 2024-07-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0008_contactsgl_created_at_taskitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='task_id',
        ),
    ]
