# Generated by Django 4.2.14 on 2024-07-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0009_remove_taskitem_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='text',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
